version: '3'

services:
    web:
        image: registry.programmerq.net/enjoy.cf
        build: .
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.middlewares.redir-https.redirectscheme.scheme=https"
                - "traefik.http.routers.sillyspectacleml.rule=Host(`enjoy.cf`)"
                - "traefik.http.routers.sillyspectacleml.middlewares=redir-https@docker"
                - "traefik.http.routers.sillyspectacleml-sec.rule=Host(`enjoy.cf`)"
                - "traefik.http.routers.sillyspectacleml-sec.tls.certresolver=mycf"
                - "traefik.http.routers.sillyspectacleml-sec.entrypoints=websecure,web"
                - "traefik.http.services.sillyspectacleml-sec.loadbalancer.server.port=80"
        networks:
            traefik:
networks:
    traefik:
        external: true
